AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nova Sonic App Runner Deployment'

Parameters:
  GitHubRepoUrl:
    Type: String
    Description: GitHub repository URL (e.g., https://github.com/username/repo)
    Default: https://github.com/your-username/novasonic-app
  
  GitHubBranch:
    Type: String
    Description: GitHub branch to deploy
    Default: main

Resources:
  # IAM Role for App Runner
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      RoleName: !Sub '${AWS::StackName}-AppRunnerInstanceRole'

  # App Runner Access Role
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      RoleName: !Sub '${AWS::StackName}-AppRunnerAccessRole'

  # App Runner Service
  NovasonicAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub '${AWS::StackName}-novasonic-app'
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: !Ref GitHubRepoUrl
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref GitHubBranch
          CodeConfiguration:
            ConfigurationSource: REPOSITORY
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-novasonic-app'
        - Key: Environment
          Value: Production

Outputs:
  AppRunnerServiceUrl:
    Description: App Runner Service URL
    Value: !Sub 'https://${NovasonicAppRunnerService.ServiceUrl}'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceUrl'
  
  AppRunnerServiceArn:
    Description: App Runner Service ARN
    Value: !Ref NovasonicAppRunnerService
    Export:
      Name: !Sub '${AWS::StackName}-ServiceArn'